Add template sections
JupiterOne/graph-npm pull request #18
Opened 2021-04-08 01:37 UTC by jayson-jensen-pro

2021-04-08 02:14 UTC, aiwilliams requested changes

2021-04-08 02:14 UTC, aiwilliams commented on docs/jupiterone.md
> +interact with the API.
```suggestion
to interact with the API.
```

2021-04-09 19:06 UTC, mknoedel approved these changes

2021-04-09 20:25 UTC, aiwilliams approved these changes

2021-04-11 21:00 UTC, merged